### ISSUE TITLE
signature has expired

### ISSUE THREAD

**Issue by prifyDevelopers** [Appollo-CLI/Appollo#21]
i got this error when i ran appollo build start and chose configuration

>appollo build start
Build type (configuration, development, ad-hoc, distribution, validation, publication): configuration
Error: ['Signature has expired.']
Traceback (most recent call last):
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Super-S\AppData\Local\Programs\Python\Python39\Scripts\appollo.exe\__main__.py", line 7, in <module>
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\appollo\helpers.py", line 54, in run
    return ctx.invoke(f, *args, **kwargs)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\appollo\commands\build.py", line 239, in start
    app_key = terminal_menu("/applications/", "Application",
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\appollo\helpers.py", line 71, in terminal_menu
    item_list = api.get(api_route)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\appollo\api.py", line 28, in get
    auth_headers = get_authorization_header(**auth_data)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\appollo\api.py", line 254, in get_authorization_header
    write_jwt_token(token)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\site-packages\appollo\settings.py", line 45, in write_jwt_token
    parser.set("auth", "JWT_TOKEN", token)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\configparser.py", line 1203, in set
    self._validate_value_types(option=option, value=value)
  File "c:\users\super-s\appdata\local\programs\python\python39\lib\configparser.py", line 1188, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

**Comment by tchavetdeuse** [comment]
Hi, I think you might have an older version of appollo because this bug was resolved, can you update with pip install -U appollo and try again?
