### ISSUE TITLE
Appollo build start configuration error

### ISSUE THREAD

**Issue by ErwanThebault** [Appollo-CLI/Appollo#7]
Hello Appollo's team,

I encountered an error doing an `appollo build start` in configuration mode. I was waiting for the build to finish but the system seemed to be blocked in an infinite loop (it was building for more than 15 minutes without any progression log).

I decided to abort the build and tried to launch `appollo build detail` or even `appollo build logs` and the following error appeared:

```python
Traceback (most recent call last):
  File "/home/<USER>/.local/bin/appollo", line 8, in <module>
    sys.exit(appollo())
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/<USER>/.local/lib/python3.8/site-packages/appollo/helpers.py", line 54, in run
    return ctx.invoke(f, *args, **kwargs)
  File "/home/<USER>/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/<USER>/.local/lib/python3.8/site-packages/appollo/commands/build.py", line 125, in detail
    key = terminal_menu("/builds/", "Builds", api_params={"all": 1}, name=build_name,
  File "/home/<USER>/.local/lib/python3.8/site-packages/appollo/helpers.py", line 72, in terminal_menu
    terminal_ready_list = [Choice(name(item), i) for i, item in enumerate(item_list)]
  File "/home/<USER>/.local/lib/python3.8/site-packages/appollo/helpers.py", line 72, in <listcomp>
    terminal_ready_list = [Choice(name(item), i) for i, item in enumerate(item_list)]
  File "/home/<USER>/.local/lib/python3.8/site-packages/appollo/commands/build.py", line 614, in build_name
    build_instance['start_time'] = build_instance['start_time'][:-3]+build_instance['start_time'][-2:]  # Remove timezone ':' otherwise it can't parse
TypeError: 'NoneType' object is not subscriptable
```

Thanks for your support.

**Comment by TheToto42** [comment]
Hello ! Your build was not started and Appollo was not able to determine its start time. You should not see this error now that your build is started (you sometimes have to wait for space on the system, I think). However, I've just created a PR to fix the bug.

**Comment by maxcmoi89** [comment]
You are right. The build machines had a hard time the last few days due to too many build being created at once. We made some changes to accommodate more builds on the build machines. 

@tchavetdeuse will check and merge the pull request for the CLI soon. 

@TheToto42, thank you for contributing to the project.
